### ISSUE TITLE
Alguem respondeu?

### ISSUE THREAD

**Issue by RodolfoSilva** [staysafebr/Selecao#13]
Não tive tempo de responde, tive que acompanhar minha esposa com na realização de alguns exames... 
Mas fiquei curioso sobre os resultados...

**Comment by ghost** [comment]
Uma pessoa enviou e vou testar o codigo. Da uma olhada no video q fiz se tiver interesse em ajudar no projeto https://m.youtube.com/watch?v=xIzi-362hzY

Enviado do meu iPhone

**Comment by staysafebr** [comment]
@RodolfoSilva eae deu uma olhada no video o que achou ? poxa fiquei meio chateado pq somente uma pessoa enviou um PULL. Tinha muito CV de qualidade ali.

**Comment by RodolfoSilva** [comment]
Vi o video sim. Muito massa. Se ainda tivesse prazo pra fazer o pull eu tentaria fazer... O problema foi justamente o que eu relatei acima... Mas achei bala a aplicação.
